# Generated by Django 2.2.4 on 2019-08-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_response_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='news_org_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='org_communication',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='org_comparision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='org_struggle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='org_sustainability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='tool_recommendation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='tool_satisfaction',
            field=models.CharField(max_length=100),
        ),
    ]
