# Generated by Django 2.2.4 on 2019-08-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_auto_20190815_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='org_comparision',
            new_name='org_comparison',
        ),
    ]
