# Generated by Django 2.2.4 on 2019-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20190815_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stopped_using',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
